# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sanb.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1177, 989)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 40, 1111, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.v1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.v1.setContentsMargins(0, 0, 0, 0)
        self.v1.setObjectName("v1")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(60, 360, 1111, 331))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.v2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.v2.setContentsMargins(0, 0, 0, 0)
        self.v2.setObjectName("v2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(60, 690, 1111, 231))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.v3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.v3.setContentsMargins(0, 0, 0, 0)
        self.v3.setObjectName("v3")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(20, 10, 71, 28))
        self.btn1.setObjectName("btn1")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 47, 881))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(100, 10, 71, 28))
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(180, 10, 71, 28))
        self.btn3.setObjectName("btn3")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(260, 10, 71, 28))
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(340, 10, 71, 28))
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(420, 10, 71, 28))
        self.btn6.setObjectName("btn6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1177, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn1.setText(_translate("MainWindow", "btn1"))
        self.label.setText(_translate("MainWindow", "三金"))
        self.label_2.setText(_translate("MainWindow", "差"))
        self.label_3.setText(_translate("MainWindow", "一号\n"
"金"))
        self.btn2.setText(_translate("MainWindow", "btn2"))
        self.btn3.setText(_translate("MainWindow", "btn3"))
        self.btn4.setText(_translate("MainWindow", "btn4"))
        self.btn5.setText(_translate("MainWindow", "btn5"))
        self.btn6.setText(_translate("MainWindow", "btn6"))
